import React, { useEffect } from "react";
import { CheckCircle2, ShieldAlert, Copy, RefreshCw, Printer } from "lucide-react";
import confetti from "canvas-confetti";

export default function SuccessScreen({
  registrationResult,
  onReset
}) {
  useEffect(() => {
    // Launch celebratory confetti burst
    try {
      confetti({
        particleCount: 80,
        spread: 70,
        origin: { y: 0.6 },
        colors: ["#f43f5e", "#fb7185", "#38bdf8", "#34d399", "#ffffff"]
      });
    } catch {
      // Confetti fallback safely ignored
    }
  }, []);

  const registrations = registrationResult?.registrations || [];
  const singleId = registrationResult?.registrationId;

  const copyToClipboard = (text) => {
    navigator.clipboard?.writeText(text);
    alert(`Copied "${text}" to clipboard!`);
  };

  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <div className="bg-[#0e121e] border border-slate-800 rounded-3xl p-8 sm:p-12 text-center shadow-2xl relative overflow-hidden">
        {/* Glow backdrop */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-80 h-32 bg-rose-500/10 blur-3xl pointer-events-none"></div>

        {/* Success Icon */}
        <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-emerald-500/20 to-emerald-700/10 border border-emerald-500/30 text-emerald-400 flex items-center justify-center mx-auto mb-6 shadow-xl shadow-emerald-950/40">
          <CheckCircle2 className="w-10 h-10 stroke-[2]" />
        </div>

        {/* Headings */}
        <h1 className="font-heading text-4xl sm:text-5xl tracking-wide text-white uppercase mb-3">
          REGISTRATION SUCCESSFUL
        </h1>
        <p className="text-base sm:text-lg text-slate-300 max-w-lg mx-auto mb-8">
          Your team registration has been submitted successfully.
        </p>

        {/* Registration IDs Card */}
        <div className="bg-[#080a11] border border-slate-800 rounded-2xl p-6 mb-8 text-left">
          <div className="flex items-center justify-between mb-4 pb-3 border-b border-slate-800/80">
            <span className="font-mono text-xs uppercase tracking-wider text-rose-400 font-semibold">
              OFFICIAL REGISTRATION ID{registrations.length > 1 ? "S" : ""}
            </span>
            <span className="font-mono text-[11px] text-slate-400">
              Generated by Server
            </span>
          </div>

          {/* List of returned registration IDs */}
          {registrations.length > 0 ? (
            <div className="space-y-3">
              {registrations.map((item, idx) => (
                <div
                  key={idx}
                  className="flex items-center justify-between p-3.5 rounded-xl bg-[#0c101b] border border-slate-800"
                >
                  <div>
                    <span className="text-xs font-mono text-slate-400 block">
                      {item.event}
                    </span>
                    <span className="font-mono text-lg font-bold text-white tracking-wide">
                      {item.registrationId || "TBS26-REGISTERED"}
                    </span>
                  </div>

                  {item.registrationId && (
                    <button
                      onClick={() => copyToClipboard(item.registrationId)}
                      className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors cursor-pointer"
                      title="Copy ID"
                    >
                      <Copy className="w-4 h-4" />
                    </button>
                  )}
                </div>
              ))}
            </div>
          ) : singleId ? (
            <div className="flex items-center justify-between p-4 rounded-xl bg-[#0c101b] border border-slate-800">
              <div>
                <span className="text-xs font-mono text-slate-400 block">
                  TEAM REGISTRATION ID
                </span>
                <span className="font-mono text-2xl font-bold text-white tracking-wider">
                  {singleId}
                </span>
              </div>
              <button
                onClick={() => copyToClipboard(singleId)}
                className="p-2.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors cursor-pointer"
                title="Copy ID"
              >
                <Copy className="w-5 h-5" />
              </button>
            </div>
          ) : (
            <div className="p-4 rounded-xl bg-[#0c101b] border border-slate-800 font-mono text-sm text-slate-300">
              Submission accepted and registered successfully.
            </div>
          )}

          <p className="mt-4 text-xs font-mono text-slate-400 text-center">
            Please save your registration ID for future reference.
          </p>
        </div>

        {/* Verification Status Notice */}
        <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 mb-8 flex items-center justify-center gap-2.5 text-xs font-mono text-slate-300">
          <ShieldAlert className="w-4 h-4 text-amber-400 shrink-0" />
          <span>Verification status: <strong className="text-amber-300 font-semibold">Pending manual verification</strong></span>
        </div>

        {/* Actions */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <button
            onClick={() => window.print()}
            className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-mono text-xs text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 border border-slate-700 transition-colors cursor-pointer"
          >
            <Printer className="w-4 h-4" />
            <span>Print Confirmation</span>
          </button>

          <button
            onClick={onReset}
            className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-heading text-lg tracking-wider text-white bg-rose-600 hover:bg-rose-500 transition-colors shadow-lg shadow-rose-950/50 cursor-pointer"
          >
            <RefreshCw className="w-4 h-4" />
            <span>REGISTER ANOTHER TEAM</span>
          </button>
        </div>
      </div>
    </div>
  );
}
